# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps :
      - task: TerraformCLI@0
        displayName: Terraform-Init
        inputs:
          command: 'init'
          allowTelemetryCollection: true

      - task: TerraformCLI@0
        displayName: Terraform-Validate
        inputs:
          command: 'validate'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        displayName: terraform-plan
        inputs:
          command: 'plan'
          environmentServiceName: 'siddhant_azure_sc'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        displayName: Terraform-Import
        inputs:
          command: 'import'
          allowTelemetryCollection: true
          resourceAddress: 'azurerm_resource_group.siddhantsingh01'
          resourceId: '/subscriptions/e25c0a93-619e-4b0f-8713-ada2c8e89425/resourceGroups/siddhantsingh01'
      - task: TerraformCLI@0
        displayName: terraform-apply
        inputs:
          command: 'apply'
          allowTelemetryCollection: true