apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-agent 
  namespace: default 
  labels:
    app: azdevops-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
        - name: majorassignmenagent
          #image: ACR_NAME/REPOSITORY_NAME:latest
          image: majorassignmenagent.azurecr.io/deployment-of-agent:latest
          env:
            - name: AZP_POOL
              valueFrom:
               secretKeyRef:
                 name: azdevop
                 key: AZP_POOL

            - name: AZP_TOKEN
              valueFrom:
               secretKeyRef:
                 name: azdevop
                 key: AZP_TOKEN
              
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azdevop
                  key: AZP_URL
                
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
            path: /var/run/docker.sock
